/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ExfuncError } from "./exfuncerror.js";

/**
 * User error response
 */
export type UserErrorData = {
  /**
   * Error message string
   */
  message?: string | undefined;
};

/**
 * User error response
 */
export class UserError extends ExfuncError {
  /** The original data that was passed to this error instance. */
  data$: UserErrorData;

  constructor(
    err: UserErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "UserError";
  }
}

/** @internal */
export const UserError$inboundSchema: z.ZodType<
  UserError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UserError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UserError$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const UserError$outboundSchema: z.ZodType<
  UserError$Outbound,
  z.ZodTypeDef,
  UserError
> = z.instanceof(UserError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserError$ {
  /** @deprecated use `UserError$inboundSchema` instead. */
  export const inboundSchema = UserError$inboundSchema;
  /** @deprecated use `UserError$outboundSchema` instead. */
  export const outboundSchema = UserError$outboundSchema;
  /** @deprecated use `UserError$Outbound` instead. */
  export type Outbound = UserError$Outbound;
}
