/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * User error response
 */
export type UserErrorData = {
  /**
   * Error message string
   */
  message?: string | undefined;
};

/**
 * User error response
 */
export class UserError extends Error {
  /** The original data that was passed to this error instance. */
  data$: UserErrorData;

  constructor(err: UserErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "UserError";
  }
}

/** @internal */
export const UserError$inboundSchema: z.ZodType<
  UserError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
})
  .transform((v) => {
    return new UserError(v);
  });

/** @internal */
export type UserError$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const UserError$outboundSchema: z.ZodType<
  UserError$Outbound,
  z.ZodTypeDef,
  UserError
> = z.instanceof(UserError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserError$ {
  /** @deprecated use `UserError$inboundSchema` instead. */
  export const inboundSchema = UserError$inboundSchema;
  /** @deprecated use `UserError$outboundSchema` instead. */
  export const outboundSchema = UserError$outboundSchema;
  /** @deprecated use `UserError$Outbound` instead. */
  export type Outbound = UserError$Outbound;
}
