/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { glassdoorSearchJobPostings } from "../funcs/glassdoorSearchJobPostings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Glassdoor extends ClientSDK {
  /**
   * Search job postings on Glassdoor
   *
   * @remarks
   * Search job postings on Glassdoor for a given query
   */
  async searchJobPostings(
    request: operations.GlassdoorSearchJobPostingsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.GlassdoorSearchJobPostingsResponseBody> {
    return unwrapAsync(glassdoorSearchJobPostings(
      this,
      request,
      options,
    ));
  }
}
