/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indeedSearchJobPostings } from "../funcs/indeedSearchJobPostings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Indeed extends ClientSDK {
  /**
   * Search job postings on Indeed
   *
   * @remarks
   * Search job postings on Indeed for a given query
   */
  async searchJobPostings(
    request: operations.IndeedSearchJobPostingsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.IndeedSearchJobPostingsResponseBody> {
    return unwrapAsync(indeedSearchJobPostings(
      this,
      request,
      options,
    ));
  }
}
