/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Google } from "./google.js";
import { Linkedin } from "./linkedin.js";
import { Navigator } from "./navigator.js";
import { Skyscanner } from "./skyscanner.js";
import { Twitter } from "./twitter.js";
import { Yelp } from "./yelp.js";
import { Zillow } from "./zillow.js";

export class Exfunc extends ClientSDK {
  private _google?: Google;
  get google(): Google {
    return (this._google ??= new Google(this._options));
  }

  private _linkedin?: Linkedin;
  get linkedin(): Linkedin {
    return (this._linkedin ??= new Linkedin(this._options));
  }

  private _navigator?: Navigator;
  get navigator(): Navigator {
    return (this._navigator ??= new Navigator(this._options));
  }

  private _skyscanner?: Skyscanner;
  get skyscanner(): Skyscanner {
    return (this._skyscanner ??= new Skyscanner(this._options));
  }

  private _twitter?: Twitter;
  get twitter(): Twitter {
    return (this._twitter ??= new Twitter(this._options));
  }

  private _yelp?: Yelp;
  get yelp(): Yelp {
    return (this._yelp ??= new Yelp(this._options));
  }

  private _zillow?: Zillow;
  get zillow(): Zillow {
    return (this._zillow ??= new Zillow(this._options));
  }
}
