/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { skyscannerSearchFlights } from "../funcs/skyscannerSearchFlights.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Skyscanner extends ClientSDK {
  /**
   * Search flights on SkyScanner
   *
   * @remarks
   * Search flights on SkyScanner for given origin, destination, departure date and return date
   */
  async searchFlights(
    request: operations.SearchFlightsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.SearchFlightsResponseBody> {
    return unwrapAsync(skyscannerSearchFlights(
      this,
      request,
      options,
    ));
  }
}
