/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { skyscannerSearchOneWay } from "../funcs/skyscannerSearchOneWay.js";
import { skyscannerSearchRoundtrip } from "../funcs/skyscannerSearchRoundtrip.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Skyscanner extends ClientSDK {
  /**
   * Search one-way flights on SkyScanner
   *
   * @remarks
   * Search one-way flights on SkyScanner for given origin, destination, and departure date
   */
  async searchOneWay(
    request: operations.SearchOneWayRequestBody,
    options?: RequestOptions,
  ): Promise<operations.SearchOneWayResponseBody> {
    return unwrapAsync(skyscannerSearchOneWay(
      this,
      request,
      options,
    ));
  }

  /**
   * Search roundtrip flights on SkyScanner
   *
   * @remarks
   * Search roundtrip flights on SkyScanner for given origin, destination, departure date and return date
   */
  async searchRoundtrip(
    request: operations.SearchRoundtripRequestBody,
    options?: RequestOptions,
  ): Promise<operations.SearchRoundtripResponseBody> {
    return unwrapAsync(skyscannerSearchRoundtrip(
      this,
      request,
      options,
    ));
  }
}
