/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { zillowGet } from "../funcs/zillowGet.js";
import { zillowSearchProperties } from "../funcs/zillowSearchProperties.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Zillow extends ClientSDK {
  /**
   * Get property details from Zillow
   *
   * @remarks
   * Get property details on Zillow for a given property ID
   */
  async get(
    request: operations.GetPropertyRequestBody,
    options?: RequestOptions,
  ): Promise<operations.GetPropertyResponseBody> {
    return unwrapAsync(zillowGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Search for properties on Zillow
   *
   * @remarks
   * Search for properties on Zillow for a given location, listing status, and other criteria
   */
  async searchProperties(
    request: operations.SearchPropertiesRequestBody,
    options?: RequestOptions,
  ): Promise<operations.SearchPropertiesResponseBody> {
    return unwrapAsync(zillowSearchProperties(
      this,
      request,
      options,
    ));
  }
}
