/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the exfunc SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx glassdoorSearchJobPostings.example.ts
 */

import { Exfunc } from "exfunc";

const exfunc = new Exfunc({
  apiKey: process.env["EXFUNC_API_KEY"] ?? "",
});

async function main() {
  const result = await exfunc.glassdoor.searchJobPostings({});

  console.log(result);
}

main().catch(console.error);
