workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    exfunc-OAS:
        inputs:
            - location: ./spec/exfunc_v1_openapi_spec.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/nunchi-4op/nunchi/exfunc-oas
targets:
    exfunc:
        target: typescript
        source: exfunc-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/nunchi-4op/nunchi/exfunc-oas-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
