/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBusinessRequestBody = {
  /**
   * The ID of the business to retrieve reviews for
   */
  businessId: string;
};

/**
 * GetBusiness API successful response
 */
export type GetBusinessResponseBody = {
  business?: components.YelpBusiness | undefined;
};

/** @internal */
export const GetBusinessRequestBody$inboundSchema: z.ZodType<
  GetBusinessRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  business_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "business_id": "businessId",
  });
});

/** @internal */
export type GetBusinessRequestBody$Outbound = {
  business_id: string;
};

/** @internal */
export const GetBusinessRequestBody$outboundSchema: z.ZodType<
  GetBusinessRequestBody$Outbound,
  z.ZodTypeDef,
  GetBusinessRequestBody
> = z.object({
  businessId: z.string(),
}).transform((v) => {
  return remap$(v, {
    businessId: "business_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBusinessRequestBody$ {
  /** @deprecated use `GetBusinessRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetBusinessRequestBody$inboundSchema;
  /** @deprecated use `GetBusinessRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetBusinessRequestBody$outboundSchema;
  /** @deprecated use `GetBusinessRequestBody$Outbound` instead. */
  export type Outbound = GetBusinessRequestBody$Outbound;
}

export function getBusinessRequestBodyToJSON(
  getBusinessRequestBody: GetBusinessRequestBody,
): string {
  return JSON.stringify(
    GetBusinessRequestBody$outboundSchema.parse(getBusinessRequestBody),
  );
}

export function getBusinessRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetBusinessRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBusinessRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBusinessRequestBody' from JSON`,
  );
}

/** @internal */
export const GetBusinessResponseBody$inboundSchema: z.ZodType<
  GetBusinessResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  business: components.YelpBusiness$inboundSchema.optional(),
});

/** @internal */
export type GetBusinessResponseBody$Outbound = {
  business?: components.YelpBusiness$Outbound | undefined;
};

/** @internal */
export const GetBusinessResponseBody$outboundSchema: z.ZodType<
  GetBusinessResponseBody$Outbound,
  z.ZodTypeDef,
  GetBusinessResponseBody
> = z.object({
  business: components.YelpBusiness$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBusinessResponseBody$ {
  /** @deprecated use `GetBusinessResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetBusinessResponseBody$inboundSchema;
  /** @deprecated use `GetBusinessResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetBusinessResponseBody$outboundSchema;
  /** @deprecated use `GetBusinessResponseBody$Outbound` instead. */
  export type Outbound = GetBusinessResponseBody$Outbound;
}

export function getBusinessResponseBodyToJSON(
  getBusinessResponseBody: GetBusinessResponseBody,
): string {
  return JSON.stringify(
    GetBusinessResponseBody$outboundSchema.parse(getBusinessResponseBody),
  );
}

export function getBusinessResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetBusinessResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBusinessResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBusinessResponseBody' from JSON`,
  );
}
