/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetPersonRequestBody = {
  /**
   * The URL of the person to enrich
   */
  personUrl: string;
};

/**
 * GetPerson API successful response
 */
export type GetPersonResponseBody = {
  person?: components.LinkedInPerson | undefined;
};

/** @internal */
export const GetPersonRequestBody$inboundSchema: z.ZodType<
  GetPersonRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  person_url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "person_url": "personUrl",
  });
});

/** @internal */
export type GetPersonRequestBody$Outbound = {
  person_url: string;
};

/** @internal */
export const GetPersonRequestBody$outboundSchema: z.ZodType<
  GetPersonRequestBody$Outbound,
  z.ZodTypeDef,
  GetPersonRequestBody
> = z.object({
  personUrl: z.string(),
}).transform((v) => {
  return remap$(v, {
    personUrl: "person_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPersonRequestBody$ {
  /** @deprecated use `GetPersonRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetPersonRequestBody$inboundSchema;
  /** @deprecated use `GetPersonRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetPersonRequestBody$outboundSchema;
  /** @deprecated use `GetPersonRequestBody$Outbound` instead. */
  export type Outbound = GetPersonRequestBody$Outbound;
}

/** @internal */
export const GetPersonResponseBody$inboundSchema: z.ZodType<
  GetPersonResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  person: components.LinkedInPerson$inboundSchema.optional(),
});

/** @internal */
export type GetPersonResponseBody$Outbound = {
  person?: components.LinkedInPerson$Outbound | undefined;
};

/** @internal */
export const GetPersonResponseBody$outboundSchema: z.ZodType<
  GetPersonResponseBody$Outbound,
  z.ZodTypeDef,
  GetPersonResponseBody
> = z.object({
  person: components.LinkedInPerson$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPersonResponseBody$ {
  /** @deprecated use `GetPersonResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetPersonResponseBody$inboundSchema;
  /** @deprecated use `GetPersonResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetPersonResponseBody$outboundSchema;
  /** @deprecated use `GetPersonResponseBody$Outbound` instead. */
  export type Outbound = GetPersonResponseBody$Outbound;
}
