/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTweetRequestBody = {
  /**
   * The ID of the tweet to retrieve
   */
  tweetId: string;
};

/**
 * GetTweet API successful response
 */
export type GetTweetResponseBody = {
  tweet?: components.Tweet | undefined;
};

/** @internal */
export const GetTweetRequestBody$inboundSchema: z.ZodType<
  GetTweetRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  tweet_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "tweet_id": "tweetId",
  });
});

/** @internal */
export type GetTweetRequestBody$Outbound = {
  tweet_id: string;
};

/** @internal */
export const GetTweetRequestBody$outboundSchema: z.ZodType<
  GetTweetRequestBody$Outbound,
  z.ZodTypeDef,
  GetTweetRequestBody
> = z.object({
  tweetId: z.string(),
}).transform((v) => {
  return remap$(v, {
    tweetId: "tweet_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTweetRequestBody$ {
  /** @deprecated use `GetTweetRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetTweetRequestBody$inboundSchema;
  /** @deprecated use `GetTweetRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetTweetRequestBody$outboundSchema;
  /** @deprecated use `GetTweetRequestBody$Outbound` instead. */
  export type Outbound = GetTweetRequestBody$Outbound;
}

export function getTweetRequestBodyToJSON(
  getTweetRequestBody: GetTweetRequestBody,
): string {
  return JSON.stringify(
    GetTweetRequestBody$outboundSchema.parse(getTweetRequestBody),
  );
}

export function getTweetRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetTweetRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTweetRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTweetRequestBody' from JSON`,
  );
}

/** @internal */
export const GetTweetResponseBody$inboundSchema: z.ZodType<
  GetTweetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  tweet: components.Tweet$inboundSchema.optional(),
});

/** @internal */
export type GetTweetResponseBody$Outbound = {
  tweet?: components.Tweet$Outbound | undefined;
};

/** @internal */
export const GetTweetResponseBody$outboundSchema: z.ZodType<
  GetTweetResponseBody$Outbound,
  z.ZodTypeDef,
  GetTweetResponseBody
> = z.object({
  tweet: components.Tweet$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTweetResponseBody$ {
  /** @deprecated use `GetTweetResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetTweetResponseBody$inboundSchema;
  /** @deprecated use `GetTweetResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetTweetResponseBody$outboundSchema;
  /** @deprecated use `GetTweetResponseBody$Outbound` instead. */
  export type Outbound = GetTweetResponseBody$Outbound;
}

export function getTweetResponseBodyToJSON(
  getTweetResponseBody: GetTweetResponseBody,
): string {
  return JSON.stringify(
    GetTweetResponseBody$outboundSchema.parse(getTweetResponseBody),
  );
}

export function getTweetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetTweetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTweetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTweetResponseBody' from JSON`,
  );
}
