/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetTweetRequestBody = {
  /**
   * The ID of the tweet to retrieve
   */
  tweetId: string;
};

/**
 * GetTweet API successful response
 */
export type GetTweetResponseBody = {
  tweet?: components.Tweet | undefined;
};

/** @internal */
export const GetTweetRequestBody$inboundSchema: z.ZodType<
  GetTweetRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  tweet_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "tweet_id": "tweetId",
  });
});

/** @internal */
export type GetTweetRequestBody$Outbound = {
  tweet_id: string;
};

/** @internal */
export const GetTweetRequestBody$outboundSchema: z.ZodType<
  GetTweetRequestBody$Outbound,
  z.ZodTypeDef,
  GetTweetRequestBody
> = z.object({
  tweetId: z.string(),
}).transform((v) => {
  return remap$(v, {
    tweetId: "tweet_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTweetRequestBody$ {
  /** @deprecated use `GetTweetRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetTweetRequestBody$inboundSchema;
  /** @deprecated use `GetTweetRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetTweetRequestBody$outboundSchema;
  /** @deprecated use `GetTweetRequestBody$Outbound` instead. */
  export type Outbound = GetTweetRequestBody$Outbound;
}

/** @internal */
export const GetTweetResponseBody$inboundSchema: z.ZodType<
  GetTweetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  tweet: components.Tweet$inboundSchema.optional(),
});

/** @internal */
export type GetTweetResponseBody$Outbound = {
  tweet?: components.Tweet$Outbound | undefined;
};

/** @internal */
export const GetTweetResponseBody$outboundSchema: z.ZodType<
  GetTweetResponseBody$Outbound,
  z.ZodTypeDef,
  GetTweetResponseBody
> = z.object({
  tweet: components.Tweet$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTweetResponseBody$ {
  /** @deprecated use `GetTweetResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetTweetResponseBody$inboundSchema;
  /** @deprecated use `GetTweetResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetTweetResponseBody$outboundSchema;
  /** @deprecated use `GetTweetResponseBody$Outbound` instead. */
  export type Outbound = GetTweetResponseBody$Outbound;
}
