/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserFollowersRequestBody = {
  /**
   * The username of the Twitter user whose followers to retrieve
   */
  username: string;
  /**
   * The number of followers to retrieve
   */
  count?: number | undefined;
};

/**
 * GetUserFollowers API successful response
 */
export type GetUserFollowersResponseBody = {
  followers?: Array<components.TwitterUser> | undefined;
};

/** @internal */
export const GetUserFollowersRequestBody$inboundSchema: z.ZodType<
  GetUserFollowersRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  username: z.string(),
  count: z.number().int().optional(),
});

/** @internal */
export type GetUserFollowersRequestBody$Outbound = {
  username: string;
  count?: number | undefined;
};

/** @internal */
export const GetUserFollowersRequestBody$outboundSchema: z.ZodType<
  GetUserFollowersRequestBody$Outbound,
  z.ZodTypeDef,
  GetUserFollowersRequestBody
> = z.object({
  username: z.string(),
  count: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserFollowersRequestBody$ {
  /** @deprecated use `GetUserFollowersRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetUserFollowersRequestBody$inboundSchema;
  /** @deprecated use `GetUserFollowersRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetUserFollowersRequestBody$outboundSchema;
  /** @deprecated use `GetUserFollowersRequestBody$Outbound` instead. */
  export type Outbound = GetUserFollowersRequestBody$Outbound;
}

export function getUserFollowersRequestBodyToJSON(
  getUserFollowersRequestBody: GetUserFollowersRequestBody,
): string {
  return JSON.stringify(
    GetUserFollowersRequestBody$outboundSchema.parse(
      getUserFollowersRequestBody,
    ),
  );
}

export function getUserFollowersRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetUserFollowersRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserFollowersRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserFollowersRequestBody' from JSON`,
  );
}

/** @internal */
export const GetUserFollowersResponseBody$inboundSchema: z.ZodType<
  GetUserFollowersResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  followers: z.array(components.TwitterUser$inboundSchema).optional(),
});

/** @internal */
export type GetUserFollowersResponseBody$Outbound = {
  followers?: Array<components.TwitterUser$Outbound> | undefined;
};

/** @internal */
export const GetUserFollowersResponseBody$outboundSchema: z.ZodType<
  GetUserFollowersResponseBody$Outbound,
  z.ZodTypeDef,
  GetUserFollowersResponseBody
> = z.object({
  followers: z.array(components.TwitterUser$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserFollowersResponseBody$ {
  /** @deprecated use `GetUserFollowersResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetUserFollowersResponseBody$inboundSchema;
  /** @deprecated use `GetUserFollowersResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetUserFollowersResponseBody$outboundSchema;
  /** @deprecated use `GetUserFollowersResponseBody$Outbound` instead. */
  export type Outbound = GetUserFollowersResponseBody$Outbound;
}

export function getUserFollowersResponseBodyToJSON(
  getUserFollowersResponseBody: GetUserFollowersResponseBody,
): string {
  return JSON.stringify(
    GetUserFollowersResponseBody$outboundSchema.parse(
      getUserFollowersResponseBody,
    ),
  );
}

export function getUserFollowersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetUserFollowersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserFollowersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserFollowersResponseBody' from JSON`,
  );
}
