/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type GetUserFollowingsRequestBody = {
  /**
   * The username of the Twitter user whose followings to retrieve
   */
  username: string;
  /**
   * The number of followings to retrieve
   */
  count?: number | undefined;
};

/**
 * GetUserFollowings API successful response
 */
export type GetUserFollowingsResponseBody = {
  followings?: Array<components.TwitterUser> | undefined;
};

/** @internal */
export const GetUserFollowingsRequestBody$inboundSchema: z.ZodType<
  GetUserFollowingsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  username: z.string(),
  count: z.number().int().optional(),
});

/** @internal */
export type GetUserFollowingsRequestBody$Outbound = {
  username: string;
  count?: number | undefined;
};

/** @internal */
export const GetUserFollowingsRequestBody$outboundSchema: z.ZodType<
  GetUserFollowingsRequestBody$Outbound,
  z.ZodTypeDef,
  GetUserFollowingsRequestBody
> = z.object({
  username: z.string(),
  count: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserFollowingsRequestBody$ {
  /** @deprecated use `GetUserFollowingsRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetUserFollowingsRequestBody$inboundSchema;
  /** @deprecated use `GetUserFollowingsRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetUserFollowingsRequestBody$outboundSchema;
  /** @deprecated use `GetUserFollowingsRequestBody$Outbound` instead. */
  export type Outbound = GetUserFollowingsRequestBody$Outbound;
}

/** @internal */
export const GetUserFollowingsResponseBody$inboundSchema: z.ZodType<
  GetUserFollowingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  followings: z.array(components.TwitterUser$inboundSchema).optional(),
});

/** @internal */
export type GetUserFollowingsResponseBody$Outbound = {
  followings?: Array<components.TwitterUser$Outbound> | undefined;
};

/** @internal */
export const GetUserFollowingsResponseBody$outboundSchema: z.ZodType<
  GetUserFollowingsResponseBody$Outbound,
  z.ZodTypeDef,
  GetUserFollowingsResponseBody
> = z.object({
  followings: z.array(components.TwitterUser$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserFollowingsResponseBody$ {
  /** @deprecated use `GetUserFollowingsResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetUserFollowingsResponseBody$inboundSchema;
  /** @deprecated use `GetUserFollowingsResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetUserFollowingsResponseBody$outboundSchema;
  /** @deprecated use `GetUserFollowingsResponseBody$Outbound` instead. */
  export type Outbound = GetUserFollowingsResponseBody$Outbound;
}
