/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type GetUserTweetsRequestBody = {
  /**
   * The username of the Twitter user whose tweets to retrieve
   */
  username: string;
  /**
   * The number of tweets to retrieve
   */
  count?: number | undefined;
};

/**
 * GetUserTweets API successful response
 */
export type GetUserTweetsResponseBody = {
  tweets?: Array<components.Tweet> | undefined;
};

/** @internal */
export const GetUserTweetsRequestBody$inboundSchema: z.ZodType<
  GetUserTweetsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  username: z.string(),
  count: z.number().int().optional(),
});

/** @internal */
export type GetUserTweetsRequestBody$Outbound = {
  username: string;
  count?: number | undefined;
};

/** @internal */
export const GetUserTweetsRequestBody$outboundSchema: z.ZodType<
  GetUserTweetsRequestBody$Outbound,
  z.ZodTypeDef,
  GetUserTweetsRequestBody
> = z.object({
  username: z.string(),
  count: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserTweetsRequestBody$ {
  /** @deprecated use `GetUserTweetsRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetUserTweetsRequestBody$inboundSchema;
  /** @deprecated use `GetUserTweetsRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetUserTweetsRequestBody$outboundSchema;
  /** @deprecated use `GetUserTweetsRequestBody$Outbound` instead. */
  export type Outbound = GetUserTweetsRequestBody$Outbound;
}

/** @internal */
export const GetUserTweetsResponseBody$inboundSchema: z.ZodType<
  GetUserTweetsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  tweets: z.array(components.Tweet$inboundSchema).optional(),
});

/** @internal */
export type GetUserTweetsResponseBody$Outbound = {
  tweets?: Array<components.Tweet$Outbound> | undefined;
};

/** @internal */
export const GetUserTweetsResponseBody$outboundSchema: z.ZodType<
  GetUserTweetsResponseBody$Outbound,
  z.ZodTypeDef,
  GetUserTweetsResponseBody
> = z.object({
  tweets: z.array(components.Tweet$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserTweetsResponseBody$ {
  /** @deprecated use `GetUserTweetsResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetUserTweetsResponseBody$inboundSchema;
  /** @deprecated use `GetUserTweetsResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetUserTweetsResponseBody$outboundSchema;
  /** @deprecated use `GetUserTweetsResponseBody$Outbound` instead. */
  export type Outbound = GetUserTweetsResponseBody$Outbound;
}
