/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GoogleGetJobPostingRequestBody = {
  /**
   * The ID of the job posting to retrieve
   */
  jobPostingId: string;
};

/**
 * GetJobPosting API successful response
 */
export type GoogleGetJobPostingResponseBody = {
  jobPosting?: components.GoogleJobPosting | undefined;
};

/** @internal */
export const GoogleGetJobPostingRequestBody$inboundSchema: z.ZodType<
  GoogleGetJobPostingRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  job_posting_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "job_posting_id": "jobPostingId",
  });
});

/** @internal */
export type GoogleGetJobPostingRequestBody$Outbound = {
  job_posting_id: string;
};

/** @internal */
export const GoogleGetJobPostingRequestBody$outboundSchema: z.ZodType<
  GoogleGetJobPostingRequestBody$Outbound,
  z.ZodTypeDef,
  GoogleGetJobPostingRequestBody
> = z.object({
  jobPostingId: z.string(),
}).transform((v) => {
  return remap$(v, {
    jobPostingId: "job_posting_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GoogleGetJobPostingRequestBody$ {
  /** @deprecated use `GoogleGetJobPostingRequestBody$inboundSchema` instead. */
  export const inboundSchema = GoogleGetJobPostingRequestBody$inboundSchema;
  /** @deprecated use `GoogleGetJobPostingRequestBody$outboundSchema` instead. */
  export const outboundSchema = GoogleGetJobPostingRequestBody$outboundSchema;
  /** @deprecated use `GoogleGetJobPostingRequestBody$Outbound` instead. */
  export type Outbound = GoogleGetJobPostingRequestBody$Outbound;
}

export function googleGetJobPostingRequestBodyToJSON(
  googleGetJobPostingRequestBody: GoogleGetJobPostingRequestBody,
): string {
  return JSON.stringify(
    GoogleGetJobPostingRequestBody$outboundSchema.parse(
      googleGetJobPostingRequestBody,
    ),
  );
}

export function googleGetJobPostingRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<GoogleGetJobPostingRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoogleGetJobPostingRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoogleGetJobPostingRequestBody' from JSON`,
  );
}

/** @internal */
export const GoogleGetJobPostingResponseBody$inboundSchema: z.ZodType<
  GoogleGetJobPostingResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  job_posting: components.GoogleJobPosting$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "job_posting": "jobPosting",
  });
});

/** @internal */
export type GoogleGetJobPostingResponseBody$Outbound = {
  job_posting?: components.GoogleJobPosting$Outbound | undefined;
};

/** @internal */
export const GoogleGetJobPostingResponseBody$outboundSchema: z.ZodType<
  GoogleGetJobPostingResponseBody$Outbound,
  z.ZodTypeDef,
  GoogleGetJobPostingResponseBody
> = z.object({
  jobPosting: components.GoogleJobPosting$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    jobPosting: "job_posting",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GoogleGetJobPostingResponseBody$ {
  /** @deprecated use `GoogleGetJobPostingResponseBody$inboundSchema` instead. */
  export const inboundSchema = GoogleGetJobPostingResponseBody$inboundSchema;
  /** @deprecated use `GoogleGetJobPostingResponseBody$outboundSchema` instead. */
  export const outboundSchema = GoogleGetJobPostingResponseBody$outboundSchema;
  /** @deprecated use `GoogleGetJobPostingResponseBody$Outbound` instead. */
  export type Outbound = GoogleGetJobPostingResponseBody$Outbound;
}

export function googleGetJobPostingResponseBodyToJSON(
  googleGetJobPostingResponseBody: GoogleGetJobPostingResponseBody,
): string {
  return JSON.stringify(
    GoogleGetJobPostingResponseBody$outboundSchema.parse(
      googleGetJobPostingResponseBody,
    ),
  );
}

export function googleGetJobPostingResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GoogleGetJobPostingResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoogleGetJobPostingResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoogleGetJobPostingResponseBody' from JSON`,
  );
}
