/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filter for job postings based on when they were posted
 */
export const IndeedSearchJobPostingsDatePosted = {
  AnyTime: "Any time",
  Past24Hours: "Past 24 hours",
  Past3Days: "Past 3 days",
  PastWeek: "Past Week",
  PastMonth: "Past Month",
} as const;
/**
 * Filter for job postings based on when they were posted
 */
export type IndeedSearchJobPostingsDatePosted = ClosedEnum<
  typeof IndeedSearchJobPostingsDatePosted
>;

export type IndeedSearchJobPostingsRequestBody = {
  /**
   * The search query for job postings
   */
  query?: string | undefined;
  /**
   * Location to filter job postings
   */
  location?: string | undefined;
  /**
   * Filter for job postings based on when they were posted
   */
  datePosted?: IndeedSearchJobPostingsDatePosted | undefined;
  /**
   * Next token for pagination
   */
  nextToken?: string | null | undefined;
};

/**
 * SearchJobPostings API successful response
 */
export type IndeedSearchJobPostingsResponseBody = {
  jobPostings?: Array<components.IndeedJobPosting> | undefined;
};

/** @internal */
export const IndeedSearchJobPostingsDatePosted$inboundSchema: z.ZodNativeEnum<
  typeof IndeedSearchJobPostingsDatePosted
> = z.nativeEnum(IndeedSearchJobPostingsDatePosted);

/** @internal */
export const IndeedSearchJobPostingsDatePosted$outboundSchema: z.ZodNativeEnum<
  typeof IndeedSearchJobPostingsDatePosted
> = IndeedSearchJobPostingsDatePosted$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IndeedSearchJobPostingsDatePosted$ {
  /** @deprecated use `IndeedSearchJobPostingsDatePosted$inboundSchema` instead. */
  export const inboundSchema = IndeedSearchJobPostingsDatePosted$inboundSchema;
  /** @deprecated use `IndeedSearchJobPostingsDatePosted$outboundSchema` instead. */
  export const outboundSchema =
    IndeedSearchJobPostingsDatePosted$outboundSchema;
}

/** @internal */
export const IndeedSearchJobPostingsRequestBody$inboundSchema: z.ZodType<
  IndeedSearchJobPostingsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string().optional(),
  location: z.string().optional(),
  date_posted: IndeedSearchJobPostingsDatePosted$inboundSchema.optional(),
  next_token: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "date_posted": "datePosted",
    "next_token": "nextToken",
  });
});

/** @internal */
export type IndeedSearchJobPostingsRequestBody$Outbound = {
  query?: string | undefined;
  location?: string | undefined;
  date_posted?: string | undefined;
  next_token?: string | null | undefined;
};

/** @internal */
export const IndeedSearchJobPostingsRequestBody$outboundSchema: z.ZodType<
  IndeedSearchJobPostingsRequestBody$Outbound,
  z.ZodTypeDef,
  IndeedSearchJobPostingsRequestBody
> = z.object({
  query: z.string().optional(),
  location: z.string().optional(),
  datePosted: IndeedSearchJobPostingsDatePosted$outboundSchema.optional(),
  nextToken: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    datePosted: "date_posted",
    nextToken: "next_token",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IndeedSearchJobPostingsRequestBody$ {
  /** @deprecated use `IndeedSearchJobPostingsRequestBody$inboundSchema` instead. */
  export const inboundSchema = IndeedSearchJobPostingsRequestBody$inboundSchema;
  /** @deprecated use `IndeedSearchJobPostingsRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    IndeedSearchJobPostingsRequestBody$outboundSchema;
  /** @deprecated use `IndeedSearchJobPostingsRequestBody$Outbound` instead. */
  export type Outbound = IndeedSearchJobPostingsRequestBody$Outbound;
}

export function indeedSearchJobPostingsRequestBodyToJSON(
  indeedSearchJobPostingsRequestBody: IndeedSearchJobPostingsRequestBody,
): string {
  return JSON.stringify(
    IndeedSearchJobPostingsRequestBody$outboundSchema.parse(
      indeedSearchJobPostingsRequestBody,
    ),
  );
}

export function indeedSearchJobPostingsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<IndeedSearchJobPostingsRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IndeedSearchJobPostingsRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndeedSearchJobPostingsRequestBody' from JSON`,
  );
}

/** @internal */
export const IndeedSearchJobPostingsResponseBody$inboundSchema: z.ZodType<
  IndeedSearchJobPostingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  job_postings: z.array(components.IndeedJobPosting$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "job_postings": "jobPostings",
  });
});

/** @internal */
export type IndeedSearchJobPostingsResponseBody$Outbound = {
  job_postings?: Array<components.IndeedJobPosting$Outbound> | undefined;
};

/** @internal */
export const IndeedSearchJobPostingsResponseBody$outboundSchema: z.ZodType<
  IndeedSearchJobPostingsResponseBody$Outbound,
  z.ZodTypeDef,
  IndeedSearchJobPostingsResponseBody
> = z.object({
  jobPostings: z.array(components.IndeedJobPosting$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    jobPostings: "job_postings",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IndeedSearchJobPostingsResponseBody$ {
  /** @deprecated use `IndeedSearchJobPostingsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    IndeedSearchJobPostingsResponseBody$inboundSchema;
  /** @deprecated use `IndeedSearchJobPostingsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    IndeedSearchJobPostingsResponseBody$outboundSchema;
  /** @deprecated use `IndeedSearchJobPostingsResponseBody$Outbound` instead. */
  export type Outbound = IndeedSearchJobPostingsResponseBody$Outbound;
}

export function indeedSearchJobPostingsResponseBodyToJSON(
  indeedSearchJobPostingsResponseBody: IndeedSearchJobPostingsResponseBody,
): string {
  return JSON.stringify(
    IndeedSearchJobPostingsResponseBody$outboundSchema.parse(
      indeedSearchJobPostingsResponseBody,
    ),
  );
}

export function indeedSearchJobPostingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IndeedSearchJobPostingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IndeedSearchJobPostingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndeedSearchJobPostingsResponseBody' from JSON`,
  );
}
