/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ScrapeRequestBody = {
  /**
   * The URL to start navigating from
   */
  url: string;
};

/**
 * Scrape API successful response
 */
export type ScrapeResponseBody = {
  /**
   * The page html of the website
   */
  html?: string | undefined;
  /**
   * The markdown string of the page
   */
  markdown?: string | undefined;
};

/** @internal */
export const ScrapeRequestBody$inboundSchema: z.ZodType<
  ScrapeRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
});

/** @internal */
export type ScrapeRequestBody$Outbound = {
  url: string;
};

/** @internal */
export const ScrapeRequestBody$outboundSchema: z.ZodType<
  ScrapeRequestBody$Outbound,
  z.ZodTypeDef,
  ScrapeRequestBody
> = z.object({
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScrapeRequestBody$ {
  /** @deprecated use `ScrapeRequestBody$inboundSchema` instead. */
  export const inboundSchema = ScrapeRequestBody$inboundSchema;
  /** @deprecated use `ScrapeRequestBody$outboundSchema` instead. */
  export const outboundSchema = ScrapeRequestBody$outboundSchema;
  /** @deprecated use `ScrapeRequestBody$Outbound` instead. */
  export type Outbound = ScrapeRequestBody$Outbound;
}

export function scrapeRequestBodyToJSON(
  scrapeRequestBody: ScrapeRequestBody,
): string {
  return JSON.stringify(
    ScrapeRequestBody$outboundSchema.parse(scrapeRequestBody),
  );
}

export function scrapeRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<ScrapeRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScrapeRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScrapeRequestBody' from JSON`,
  );
}

/** @internal */
export const ScrapeResponseBody$inboundSchema: z.ZodType<
  ScrapeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  html: z.string().optional(),
  markdown: z.string().optional(),
});

/** @internal */
export type ScrapeResponseBody$Outbound = {
  html?: string | undefined;
  markdown?: string | undefined;
};

/** @internal */
export const ScrapeResponseBody$outboundSchema: z.ZodType<
  ScrapeResponseBody$Outbound,
  z.ZodTypeDef,
  ScrapeResponseBody
> = z.object({
  html: z.string().optional(),
  markdown: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScrapeResponseBody$ {
  /** @deprecated use `ScrapeResponseBody$inboundSchema` instead. */
  export const inboundSchema = ScrapeResponseBody$inboundSchema;
  /** @deprecated use `ScrapeResponseBody$outboundSchema` instead. */
  export const outboundSchema = ScrapeResponseBody$outboundSchema;
  /** @deprecated use `ScrapeResponseBody$Outbound` instead. */
  export type Outbound = ScrapeResponseBody$Outbound;
}

export function scrapeResponseBodyToJSON(
  scrapeResponseBody: ScrapeResponseBody,
): string {
  return JSON.stringify(
    ScrapeResponseBody$outboundSchema.parse(scrapeResponseBody),
  );
}

export function scrapeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ScrapeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScrapeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScrapeResponseBody' from JSON`,
  );
}
