/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The type of the flight
 */
export const FlightType = {
  OneWay: "one-way",
  Roundtrip: "roundtrip",
} as const;
/**
 * The type of the flight
 */
export type FlightType = ClosedEnum<typeof FlightType>;

export const Stops = {
  Direct: "Direct",
  OneStop: "1 Stop",
  TwoPlusStops: "2+ Stops",
} as const;
export type Stops = ClosedEnum<typeof Stops>;

/**
 * The cabin class filter
 */
export const CabinClass = {
  Economy: "economy",
  PremiumEconomy: "premium_economy",
  Business: "business",
  First: "first",
} as const;
/**
 * The cabin class filter
 */
export type CabinClass = ClosedEnum<typeof CabinClass>;

export type SearchFlightsRequestBody = {
  /**
   * The origin location of the itinerary
   */
  origin: string;
  /**
   * The destination location of the itinerary
   */
  destination: string;
  /**
   * The type of the flight
   */
  flightType: FlightType;
  /**
   * The departure date of the itinerary. The format has to be YYYY-MM-DD
   */
  departDate: string;
  /**
   * The return date of the itinerary. The format has to be YYYY-MM-DD. If the flight type is roundtrip, this field is required.
   */
  returnDate?: string | undefined;
  /**
   * The list of filter values for number of stops
   */
  stops?: Array<Stops> | undefined;
  /**
   * The number of adults for the itinerary
   */
  numAdults?: number | undefined;
  /**
   * The number of children for the itinerary
   */
  numChildren?: number | undefined;
  /**
   * The number of infants for the itinerary
   */
  numInfants?: number | undefined;
  /**
   * The cabin class filter
   */
  cabinClass?: CabinClass | undefined;
  /**
   * Boolean to indicate whether to include nearby origin airports in the results or not
   */
  includeOriginNearbyAirports?: boolean | undefined;
  /**
   * Boolean to indicate whether to include nearby destination airports in the results or not
   */
  includeDestinationNearbyAirports?: boolean | undefined;
};

/**
 * SearchFlights API successful response
 */
export type SearchFlightsResponseBody = {
  itineraries?: Array<components.SkyScannerItinerary> | undefined;
};

/** @internal */
export const FlightType$inboundSchema: z.ZodNativeEnum<typeof FlightType> = z
  .nativeEnum(FlightType);

/** @internal */
export const FlightType$outboundSchema: z.ZodNativeEnum<typeof FlightType> =
  FlightType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlightType$ {
  /** @deprecated use `FlightType$inboundSchema` instead. */
  export const inboundSchema = FlightType$inboundSchema;
  /** @deprecated use `FlightType$outboundSchema` instead. */
  export const outboundSchema = FlightType$outboundSchema;
}

/** @internal */
export const Stops$inboundSchema: z.ZodNativeEnum<typeof Stops> = z.nativeEnum(
  Stops,
);

/** @internal */
export const Stops$outboundSchema: z.ZodNativeEnum<typeof Stops> =
  Stops$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Stops$ {
  /** @deprecated use `Stops$inboundSchema` instead. */
  export const inboundSchema = Stops$inboundSchema;
  /** @deprecated use `Stops$outboundSchema` instead. */
  export const outboundSchema = Stops$outboundSchema;
}

/** @internal */
export const CabinClass$inboundSchema: z.ZodNativeEnum<typeof CabinClass> = z
  .nativeEnum(CabinClass);

/** @internal */
export const CabinClass$outboundSchema: z.ZodNativeEnum<typeof CabinClass> =
  CabinClass$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CabinClass$ {
  /** @deprecated use `CabinClass$inboundSchema` instead. */
  export const inboundSchema = CabinClass$inboundSchema;
  /** @deprecated use `CabinClass$outboundSchema` instead. */
  export const outboundSchema = CabinClass$outboundSchema;
}

/** @internal */
export const SearchFlightsRequestBody$inboundSchema: z.ZodType<
  SearchFlightsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  origin: z.string(),
  destination: z.string(),
  flight_type: FlightType$inboundSchema,
  depart_date: z.string(),
  return_date: z.string().optional(),
  stops: z.array(Stops$inboundSchema).optional(),
  num_adults: z.number().default(1),
  num_children: z.number().default(0),
  num_infants: z.number().default(0),
  cabin_class: CabinClass$inboundSchema.optional(),
  include_origin_nearby_airports: z.boolean().default(false),
  include_destination_nearby_airports: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "flight_type": "flightType",
    "depart_date": "departDate",
    "return_date": "returnDate",
    "num_adults": "numAdults",
    "num_children": "numChildren",
    "num_infants": "numInfants",
    "cabin_class": "cabinClass",
    "include_origin_nearby_airports": "includeOriginNearbyAirports",
    "include_destination_nearby_airports": "includeDestinationNearbyAirports",
  });
});

/** @internal */
export type SearchFlightsRequestBody$Outbound = {
  origin: string;
  destination: string;
  flight_type: string;
  depart_date: string;
  return_date?: string | undefined;
  stops?: Array<string> | undefined;
  num_adults: number;
  num_children: number;
  num_infants: number;
  cabin_class?: string | undefined;
  include_origin_nearby_airports: boolean;
  include_destination_nearby_airports: boolean;
};

/** @internal */
export const SearchFlightsRequestBody$outboundSchema: z.ZodType<
  SearchFlightsRequestBody$Outbound,
  z.ZodTypeDef,
  SearchFlightsRequestBody
> = z.object({
  origin: z.string(),
  destination: z.string(),
  flightType: FlightType$outboundSchema,
  departDate: z.string(),
  returnDate: z.string().optional(),
  stops: z.array(Stops$outboundSchema).optional(),
  numAdults: z.number().default(1),
  numChildren: z.number().default(0),
  numInfants: z.number().default(0),
  cabinClass: CabinClass$outboundSchema.optional(),
  includeOriginNearbyAirports: z.boolean().default(false),
  includeDestinationNearbyAirports: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    flightType: "flight_type",
    departDate: "depart_date",
    returnDate: "return_date",
    numAdults: "num_adults",
    numChildren: "num_children",
    numInfants: "num_infants",
    cabinClass: "cabin_class",
    includeOriginNearbyAirports: "include_origin_nearby_airports",
    includeDestinationNearbyAirports: "include_destination_nearby_airports",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchFlightsRequestBody$ {
  /** @deprecated use `SearchFlightsRequestBody$inboundSchema` instead. */
  export const inboundSchema = SearchFlightsRequestBody$inboundSchema;
  /** @deprecated use `SearchFlightsRequestBody$outboundSchema` instead. */
  export const outboundSchema = SearchFlightsRequestBody$outboundSchema;
  /** @deprecated use `SearchFlightsRequestBody$Outbound` instead. */
  export type Outbound = SearchFlightsRequestBody$Outbound;
}

export function searchFlightsRequestBodyToJSON(
  searchFlightsRequestBody: SearchFlightsRequestBody,
): string {
  return JSON.stringify(
    SearchFlightsRequestBody$outboundSchema.parse(searchFlightsRequestBody),
  );
}

export function searchFlightsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<SearchFlightsRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchFlightsRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchFlightsRequestBody' from JSON`,
  );
}

/** @internal */
export const SearchFlightsResponseBody$inboundSchema: z.ZodType<
  SearchFlightsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  itineraries: z.array(components.SkyScannerItinerary$inboundSchema).optional(),
});

/** @internal */
export type SearchFlightsResponseBody$Outbound = {
  itineraries?: Array<components.SkyScannerItinerary$Outbound> | undefined;
};

/** @internal */
export const SearchFlightsResponseBody$outboundSchema: z.ZodType<
  SearchFlightsResponseBody$Outbound,
  z.ZodTypeDef,
  SearchFlightsResponseBody
> = z.object({
  itineraries: z.array(components.SkyScannerItinerary$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchFlightsResponseBody$ {
  /** @deprecated use `SearchFlightsResponseBody$inboundSchema` instead. */
  export const inboundSchema = SearchFlightsResponseBody$inboundSchema;
  /** @deprecated use `SearchFlightsResponseBody$outboundSchema` instead. */
  export const outboundSchema = SearchFlightsResponseBody$outboundSchema;
  /** @deprecated use `SearchFlightsResponseBody$Outbound` instead. */
  export type Outbound = SearchFlightsResponseBody$Outbound;
}

export function searchFlightsResponseBodyToJSON(
  searchFlightsResponseBody: SearchFlightsResponseBody,
): string {
  return JSON.stringify(
    SearchFlightsResponseBody$outboundSchema.parse(searchFlightsResponseBody),
  );
}

export function searchFlightsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SearchFlightsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchFlightsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchFlightsResponseBody' from JSON`,
  );
}
