/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as components from "../components/index.js";

export const Stops = {
  Direct: "Direct",
  OneStop: "1 Stop",
  TwoPlusStops: "2+ Stops",
} as const;
export type Stops = ClosedEnum<typeof Stops>;

/**
 * The cabin class filter
 */
export const CabinClass = {
  Economy: "economy",
  PremiumEconomy: "premium_economy",
  Business: "business",
  First: "first",
} as const;
/**
 * The cabin class filter
 */
export type CabinClass = ClosedEnum<typeof CabinClass>;

export type SearchOneWayRequestBody = {
  /**
   * The origin location of the itinerary
   */
  origin: string;
  /**
   * The destination location of the itinerary
   */
  destination: string;
  /**
   * The departure date of the itinerary. The format has to be YYYY-MM-DD
   */
  departDate: string;
  /**
   * The list of filter values for number of stops
   */
  stops?: Array<Stops> | undefined;
  /**
   * The number of adults for the itinerary
   */
  numAdults?: number | undefined;
  /**
   * The number of children for the itinerary
   */
  numChildren?: number | undefined;
  /**
   * The number of infants for the itinerary
   */
  numInfants?: number | undefined;
  /**
   * The cabin class filter
   */
  cabinClass?: CabinClass | undefined;
  /**
   * Boolean to indicate whether to include nearby origin airports in the results or not
   */
  includeOriginNearbyAirports?: boolean | undefined;
  /**
   * Boolean to indicate whether to include nearby destination airports in the results or not
   */
  includeDestinationNearbyAirports?: boolean | undefined;
};

/**
 * SearchOneWay API successful response
 */
export type SearchOneWayResponseBody = {
  itineraries?: Array<components.SkyScannerItinerary> | undefined;
};

/** @internal */
export const Stops$inboundSchema: z.ZodNativeEnum<typeof Stops> = z.nativeEnum(
  Stops,
);

/** @internal */
export const Stops$outboundSchema: z.ZodNativeEnum<typeof Stops> =
  Stops$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Stops$ {
  /** @deprecated use `Stops$inboundSchema` instead. */
  export const inboundSchema = Stops$inboundSchema;
  /** @deprecated use `Stops$outboundSchema` instead. */
  export const outboundSchema = Stops$outboundSchema;
}

/** @internal */
export const CabinClass$inboundSchema: z.ZodNativeEnum<typeof CabinClass> = z
  .nativeEnum(CabinClass);

/** @internal */
export const CabinClass$outboundSchema: z.ZodNativeEnum<typeof CabinClass> =
  CabinClass$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CabinClass$ {
  /** @deprecated use `CabinClass$inboundSchema` instead. */
  export const inboundSchema = CabinClass$inboundSchema;
  /** @deprecated use `CabinClass$outboundSchema` instead. */
  export const outboundSchema = CabinClass$outboundSchema;
}

/** @internal */
export const SearchOneWayRequestBody$inboundSchema: z.ZodType<
  SearchOneWayRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  origin: z.string(),
  destination: z.string(),
  depart_date: z.string(),
  stops: z.array(Stops$inboundSchema).optional(),
  num_adults: z.number().default(1),
  num_children: z.number().default(0),
  num_infants: z.number().default(0),
  cabin_class: CabinClass$inboundSchema.optional(),
  include_origin_nearby_airports: z.boolean().default(false),
  include_destination_nearby_airports: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "depart_date": "departDate",
    "num_adults": "numAdults",
    "num_children": "numChildren",
    "num_infants": "numInfants",
    "cabin_class": "cabinClass",
    "include_origin_nearby_airports": "includeOriginNearbyAirports",
    "include_destination_nearby_airports": "includeDestinationNearbyAirports",
  });
});

/** @internal */
export type SearchOneWayRequestBody$Outbound = {
  origin: string;
  destination: string;
  depart_date: string;
  stops?: Array<string> | undefined;
  num_adults: number;
  num_children: number;
  num_infants: number;
  cabin_class?: string | undefined;
  include_origin_nearby_airports: boolean;
  include_destination_nearby_airports: boolean;
};

/** @internal */
export const SearchOneWayRequestBody$outboundSchema: z.ZodType<
  SearchOneWayRequestBody$Outbound,
  z.ZodTypeDef,
  SearchOneWayRequestBody
> = z.object({
  origin: z.string(),
  destination: z.string(),
  departDate: z.string(),
  stops: z.array(Stops$outboundSchema).optional(),
  numAdults: z.number().default(1),
  numChildren: z.number().default(0),
  numInfants: z.number().default(0),
  cabinClass: CabinClass$outboundSchema.optional(),
  includeOriginNearbyAirports: z.boolean().default(false),
  includeDestinationNearbyAirports: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    departDate: "depart_date",
    numAdults: "num_adults",
    numChildren: "num_children",
    numInfants: "num_infants",
    cabinClass: "cabin_class",
    includeOriginNearbyAirports: "include_origin_nearby_airports",
    includeDestinationNearbyAirports: "include_destination_nearby_airports",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchOneWayRequestBody$ {
  /** @deprecated use `SearchOneWayRequestBody$inboundSchema` instead. */
  export const inboundSchema = SearchOneWayRequestBody$inboundSchema;
  /** @deprecated use `SearchOneWayRequestBody$outboundSchema` instead. */
  export const outboundSchema = SearchOneWayRequestBody$outboundSchema;
  /** @deprecated use `SearchOneWayRequestBody$Outbound` instead. */
  export type Outbound = SearchOneWayRequestBody$Outbound;
}

/** @internal */
export const SearchOneWayResponseBody$inboundSchema: z.ZodType<
  SearchOneWayResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  itineraries: z.array(components.SkyScannerItinerary$inboundSchema).optional(),
});

/** @internal */
export type SearchOneWayResponseBody$Outbound = {
  itineraries?: Array<components.SkyScannerItinerary$Outbound> | undefined;
};

/** @internal */
export const SearchOneWayResponseBody$outboundSchema: z.ZodType<
  SearchOneWayResponseBody$Outbound,
  z.ZodTypeDef,
  SearchOneWayResponseBody
> = z.object({
  itineraries: z.array(components.SkyScannerItinerary$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchOneWayResponseBody$ {
  /** @deprecated use `SearchOneWayResponseBody$inboundSchema` instead. */
  export const inboundSchema = SearchOneWayResponseBody$inboundSchema;
  /** @deprecated use `SearchOneWayResponseBody$outboundSchema` instead. */
  export const outboundSchema = SearchOneWayResponseBody$outboundSchema;
  /** @deprecated use `SearchOneWayResponseBody$Outbound` instead. */
  export type Outbound = SearchOneWayResponseBody$Outbound;
}
