/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type SearchUsersRequestBody = {
  /**
   * The search query string
   */
  query: string;
  /**
   * The number of results to retrieve
   */
  count?: number | undefined;
};

/**
 * SearchUsers API successful response
 */
export type SearchUsersResponseBody = {
  results?: Array<components.TwitterUser> | undefined;
};

/** @internal */
export const SearchUsersRequestBody$inboundSchema: z.ZodType<
  SearchUsersRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string(),
  count: z.number().int().optional(),
});

/** @internal */
export type SearchUsersRequestBody$Outbound = {
  query: string;
  count?: number | undefined;
};

/** @internal */
export const SearchUsersRequestBody$outboundSchema: z.ZodType<
  SearchUsersRequestBody$Outbound,
  z.ZodTypeDef,
  SearchUsersRequestBody
> = z.object({
  query: z.string(),
  count: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchUsersRequestBody$ {
  /** @deprecated use `SearchUsersRequestBody$inboundSchema` instead. */
  export const inboundSchema = SearchUsersRequestBody$inboundSchema;
  /** @deprecated use `SearchUsersRequestBody$outboundSchema` instead. */
  export const outboundSchema = SearchUsersRequestBody$outboundSchema;
  /** @deprecated use `SearchUsersRequestBody$Outbound` instead. */
  export type Outbound = SearchUsersRequestBody$Outbound;
}

/** @internal */
export const SearchUsersResponseBody$inboundSchema: z.ZodType<
  SearchUsersResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(components.TwitterUser$inboundSchema).optional(),
});

/** @internal */
export type SearchUsersResponseBody$Outbound = {
  results?: Array<components.TwitterUser$Outbound> | undefined;
};

/** @internal */
export const SearchUsersResponseBody$outboundSchema: z.ZodType<
  SearchUsersResponseBody$Outbound,
  z.ZodTypeDef,
  SearchUsersResponseBody
> = z.object({
  results: z.array(components.TwitterUser$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchUsersResponseBody$ {
  /** @deprecated use `SearchUsersResponseBody$inboundSchema` instead. */
  export const inboundSchema = SearchUsersResponseBody$inboundSchema;
  /** @deprecated use `SearchUsersResponseBody$outboundSchema` instead. */
  export const outboundSchema = SearchUsersResponseBody$outboundSchema;
  /** @deprecated use `SearchUsersResponseBody$Outbound` instead. */
  export type Outbound = SearchUsersResponseBody$Outbound;
}
