/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * LinkedIn company size range used for filtering search
 */
export const LinkedInCompanySize = {
  OneMinus10: "1-10",
  ElevenMinus50: "11-50",
  FiftyOneMinus200: "51-200",
  TwoHundredAndOneMinus500: "201-500",
  FiveHundredAndOneMinus1000: "501-1000",
  OneThousandAndOneMinus5000: "1001-5000",
  FiveThousandAndOneMinus10000: "5001-10000",
  TenThousandAndOnePlus: "10001+",
} as const;
/**
 * LinkedIn company size range used for filtering search
 */
export type LinkedInCompanySize = ClosedEnum<typeof LinkedInCompanySize>;

/** @internal */
export const LinkedInCompanySize$inboundSchema: z.ZodNativeEnum<
  typeof LinkedInCompanySize
> = z.nativeEnum(LinkedInCompanySize);

/** @internal */
export const LinkedInCompanySize$outboundSchema: z.ZodNativeEnum<
  typeof LinkedInCompanySize
> = LinkedInCompanySize$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkedInCompanySize$ {
  /** @deprecated use `LinkedInCompanySize$inboundSchema` instead. */
  export const inboundSchema = LinkedInCompanySize$inboundSchema;
  /** @deprecated use `LinkedInCompanySize$outboundSchema` instead. */
  export const outboundSchema = LinkedInCompanySize$outboundSchema;
}
