/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * LinkedIn company industry tag used for filtering search
 */
export const LinkedInCompanyIndustry = {
  Accounting: "accounting",
  Agriculture: "agriculture",
  AirlinesAviation: "airlines/aviation",
  AlternativeDisputeResolution: "alternative dispute resolution",
  AlternativeMedicine: "alternative medicine",
  Animation: "animation",
  ApparelAndFashion: "apparel & fashion",
  ArchitectureAndPlanning: "architecture & planning",
  ArtsAndCrafts: "arts & crafts",
  Automotive: "automotive",
  AviationAndAerospace: "aviation & aerospace",
  Banking: "banking",
  Biotechnology: "biotechnology",
  BroadcastMedia: "broadcast media",
  BuildingMaterials: "building materials",
  BusinessSuppliesAndEquipment: "business supplies & equipment",
  CapitalMarkets: "capital markets",
  Chemicals: "chemicals",
  CivicAndSocialOrganization: "civic & social organization",
  CivilEngineering: "civil engineering",
  CommercialRealEstate: "commercial real estate",
  ComputerAndNetworkSecurity: "computer & network security",
  ComputerGames: "computer games",
  ComputerHardware: "computer hardware",
  ComputerNetworking: "computer networking",
  ComputerSoftware: "computer software",
  Construction: "construction",
  ConsumerElectronics: "consumer electronics",
  ConsumerGoods: "consumer goods",
  ConsumerServices: "consumer services",
  Cosmetics: "cosmetics",
  Dairy: "dairy",
  DefenseAndSpace: "defense & space",
  Design: "design",
  ELearning: "e-learning",
  EducationManagement: "education management",
  ElectricalElectronicManufacturing: "electrical/electronic manufacturing",
  Entertainment: "entertainment",
  EnvironmentalServices: "environmental services",
  EventsServices: "events services",
  ExecutiveOffice: "executive office",
  FacilitiesServices: "facilities services",
  Farming: "farming",
  FinancialServices: "financial services",
  FineArt: "fine art",
  Fishery: "fishery",
  FoodAndBeverages: "food & beverages",
  FoodProduction: "food production",
  FundRaising: "fund-raising",
  Furniture: "furniture",
  GamblingAndCasinos: "gambling & casinos",
  GlassCeramicsAndConcrete: "glass, ceramics & concrete",
  GovernmentAdministration: "government administration",
  GovernmentRelations: "government relations",
  GraphicDesign: "graphic design",
  HealthWellnessAndFitness: "health, wellness & fitness",
  HigherEducation: "higher education",
  HospitalAndHealthCare: "hospital & health care",
  Hospitality: "hospitality",
  HumanResources: "human resources",
  ImportAndExport: "import & export",
  IndividualAndFamilyServices: "individual & family services",
  IndustrialAutomation: "industrial automation",
  InformationServices: "information services",
  InformationTechnologyAndServices: "information technology & services",
  Insurance: "insurance",
  InternationalAffairs: "international affairs",
  InternationalTradeAndDevelopment: "international trade & development",
  Internet: "internet",
  InvestmentBanking: "investment banking",
  InvestmentManagement: "investment management",
  Judiciary: "judiciary",
  LawEnforcement: "law enforcement",
  LawPractice: "law practice",
  LegalServices: "legal services",
  LegislativeOffice: "legislative office",
  LeisureTravelAndTourism: "leisure, travel & tourism",
  Libraries: "libraries",
  LogisticsAndSupplyChain: "logistics & supply chain",
  LuxuryGoodsAndJewelry: "luxury goods & jewelry",
  Machinery: "machinery",
  ManagementConsulting: "management consulting",
  Maritime: "maritime",
  MarketResearch: "market research",
  MarketingAndAdvertising: "marketing & advertising",
  MechanicalOrIndustrialEngineering: "mechanical or industrial engineering",
  MediaProduction: "media production",
  MedicalDevices: "medical devices",
  MedicalPractice: "medical practice",
  MentalHealthCare: "mental health care",
  Military: "military",
  MiningAndMetals: "mining & metals",
  MotionPicturesAndFilm: "motion pictures & film",
  MuseumsAndInstitutions: "museums & institutions",
  Music: "music",
  Nanotechnology: "nanotechnology",
  Newspapers: "newspapers",
  NonprofitOrganizationManagement: "nonprofit organization management",
  OilAndEnergy: "oil & energy",
  OnlineMedia: "online media",
  OutsourcingOffshoring: "outsourcing/offshoring",
  PackageFreightDelivery: "package/freight delivery",
  PackagingAndContainers: "packaging & containers",
  PaperAndForestProducts: "paper & forest products",
  PerformingArts: "performing arts",
  Pharmaceuticals: "pharmaceuticals",
  Philanthropy: "philanthropy",
  Photography: "photography",
  Plastics: "plastics",
  PoliticalOrganization: "political organization",
  PrimarySecondaryEducation: "primary/secondary education",
  Printing: "printing",
  ProfessionalTrainingAndCoaching: "professional training & coaching",
  ProgramDevelopment: "program development",
  PublicPolicy: "public policy",
  PublicRelationsAndCommunications: "public relations & communications",
  PublicSafety: "public safety",
  Publishing: "publishing",
  RailroadManufacture: "railroad manufacture",
  Ranching: "ranching",
  RealEstate: "real estate",
  RecreationalFacilitiesAndServices: "recreational facilities & services",
  ReligiousInstitutions: "religious institutions",
  RenewablesAndEnvironment: "renewables & environment",
  Research: "research",
  Restaurants: "restaurants",
  Retail: "retail",
  SecurityAndInvestigations: "security & investigations",
  Semiconductors: "semiconductors",
  Shipbuilding: "shipbuilding",
  SportingGoods: "sporting goods",
  Sports: "sports",
  StaffingAndRecruiting: "staffing & recruiting",
  Supermarkets: "supermarkets",
  Telecommunications: "telecommunications",
  Textiles: "textiles",
  ThinkTanks: "think tanks",
  Tobacco: "tobacco",
  TranslationAndLocalization: "translation & localization",
  TransportationTruckingRailroad: "transportation/trucking/railroad",
  Utilities: "utilities",
  VentureCapitalAndPrivateEquity: "venture capital & private equity",
  Veterinary: "veterinary",
  Warehousing: "warehousing",
  Wholesale: "wholesale",
  WineAndSpirits: "wine & spirits",
  Wireless: "wireless",
  WritingAndEditing: "writing & editing",
} as const;
/**
 * LinkedIn company industry tag used for filtering search
 */
export type LinkedInCompanyIndustry = ClosedEnum<
  typeof LinkedInCompanyIndustry
>;

/** @internal */
export const LinkedInCompanyIndustry$inboundSchema: z.ZodNativeEnum<
  typeof LinkedInCompanyIndustry
> = z.nativeEnum(LinkedInCompanyIndustry);

/** @internal */
export const LinkedInCompanyIndustry$outboundSchema: z.ZodNativeEnum<
  typeof LinkedInCompanyIndustry
> = LinkedInCompanyIndustry$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkedInCompanyIndustry$ {
  /** @deprecated use `LinkedInCompanyIndustry$inboundSchema` instead. */
  export const inboundSchema = LinkedInCompanyIndustry$inboundSchema;
  /** @deprecated use `LinkedInCompanyIndustry$outboundSchema` instead. */
  export const outboundSchema = LinkedInCompanyIndustry$outboundSchema;
}
