/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Request = {
  /**
   * The URL to start navigating from
   */
  url?: string | undefined;
  /**
   * The natural language objective of the navigation
   */
  objective?: string | undefined;
};

export type Response = {
  /**
   * The HTML string of the page that the navigator reached
   */
  html?: string | undefined;
  /**
   * The base64-encoded string for screenshot of the page that the navigator reached
   */
  img?: string | undefined;
  /**
   * The markdown string of the page that the navigator reached
   */
  markdown?: string | undefined;
};

/**
 * The status of the navigator task
 */
export const Status = {
  Pending: "PENDING",
  InProgress: "IN_PROGRESS",
  Succeeded: "SUCCEEDED",
  Failed: "FAILED",
  TimedOut: "TIMED_OUT",
} as const;
/**
 * The status of the navigator task
 */
export type Status = ClosedEnum<typeof Status>;

export type NavigatorTask = {
  /**
   * The ID of the navigator task
   */
  taskId?: string | undefined;
  request?: Request | undefined;
  response?: Response | undefined;
  /**
   * The status of the navigator task
   */
  status?: Status | undefined;
  /**
   * The start time of the navigator task
   */
  startTime?: string | undefined;
  /**
   * The end time of the navigator task
   */
  endTime?: string | undefined;
  /**
   * The last updated time of the navigator task
   */
  lastUpdatedTime?: string | undefined;
};

/** @internal */
export const Request$inboundSchema: z.ZodType<Request, z.ZodTypeDef, unknown> =
  z.object({
    url: z.string().optional(),
    objective: z.string().optional(),
  });

/** @internal */
export type Request$Outbound = {
  url?: string | undefined;
  objective?: string | undefined;
};

/** @internal */
export const Request$outboundSchema: z.ZodType<
  Request$Outbound,
  z.ZodTypeDef,
  Request
> = z.object({
  url: z.string().optional(),
  objective: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Request$ {
  /** @deprecated use `Request$inboundSchema` instead. */
  export const inboundSchema = Request$inboundSchema;
  /** @deprecated use `Request$outboundSchema` instead. */
  export const outboundSchema = Request$outboundSchema;
  /** @deprecated use `Request$Outbound` instead. */
  export type Outbound = Request$Outbound;
}

export function requestToJSON(request: Request): string {
  return JSON.stringify(Request$outboundSchema.parse(request));
}

export function requestFromJSON(
  jsonString: string,
): SafeParseResult<Request, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Request$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Request' from JSON`,
  );
}

/** @internal */
export const Response$inboundSchema: z.ZodType<
  Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  html: z.string().optional(),
  img: z.string().optional(),
  markdown: z.string().optional(),
});

/** @internal */
export type Response$Outbound = {
  html?: string | undefined;
  img?: string | undefined;
  markdown?: string | undefined;
};

/** @internal */
export const Response$outboundSchema: z.ZodType<
  Response$Outbound,
  z.ZodTypeDef,
  Response
> = z.object({
  html: z.string().optional(),
  img: z.string().optional(),
  markdown: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Response$ {
  /** @deprecated use `Response$inboundSchema` instead. */
  export const inboundSchema = Response$inboundSchema;
  /** @deprecated use `Response$outboundSchema` instead. */
  export const outboundSchema = Response$outboundSchema;
  /** @deprecated use `Response$Outbound` instead. */
  export type Outbound = Response$Outbound;
}

export function responseToJSON(response: Response): string {
  return JSON.stringify(Response$outboundSchema.parse(response));
}

export function responseFromJSON(
  jsonString: string,
): SafeParseResult<Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Response' from JSON`,
  );
}

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const NavigatorTask$inboundSchema: z.ZodType<
  NavigatorTask,
  z.ZodTypeDef,
  unknown
> = z.object({
  task_id: z.string().optional(),
  request: z.lazy(() => Request$inboundSchema).optional(),
  response: z.lazy(() => Response$inboundSchema).optional(),
  status: Status$inboundSchema.optional(),
  start_time: z.string().optional(),
  end_time: z.string().optional(),
  last_updated_time: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
    "start_time": "startTime",
    "end_time": "endTime",
    "last_updated_time": "lastUpdatedTime",
  });
});

/** @internal */
export type NavigatorTask$Outbound = {
  task_id?: string | undefined;
  request?: Request$Outbound | undefined;
  response?: Response$Outbound | undefined;
  status?: string | undefined;
  start_time?: string | undefined;
  end_time?: string | undefined;
  last_updated_time?: string | undefined;
};

/** @internal */
export const NavigatorTask$outboundSchema: z.ZodType<
  NavigatorTask$Outbound,
  z.ZodTypeDef,
  NavigatorTask
> = z.object({
  taskId: z.string().optional(),
  request: z.lazy(() => Request$outboundSchema).optional(),
  response: z.lazy(() => Response$outboundSchema).optional(),
  status: Status$outboundSchema.optional(),
  startTime: z.string().optional(),
  endTime: z.string().optional(),
  lastUpdatedTime: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
    startTime: "start_time",
    endTime: "end_time",
    lastUpdatedTime: "last_updated_time",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NavigatorTask$ {
  /** @deprecated use `NavigatorTask$inboundSchema` instead. */
  export const inboundSchema = NavigatorTask$inboundSchema;
  /** @deprecated use `NavigatorTask$outboundSchema` instead. */
  export const outboundSchema = NavigatorTask$outboundSchema;
  /** @deprecated use `NavigatorTask$Outbound` instead. */
  export type Outbound = NavigatorTask$Outbound;
}

export function navigatorTaskToJSON(navigatorTask: NavigatorTask): string {
  return JSON.stringify(NavigatorTask$outboundSchema.parse(navigatorTask));
}

export function navigatorTaskFromJSON(
  jsonString: string,
): SafeParseResult<NavigatorTask, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NavigatorTask$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NavigatorTask' from JSON`,
  );
}
