/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The carrier details
 */
export type SkyScannerCarrier = {
  /**
   * The ID of the carrier. This is usually an airline code.
   */
  id?: string | undefined;
  /**
   * The name of the carrier
   */
  name?: string | undefined;
};

/** @internal */
export const SkyScannerCarrier$inboundSchema: z.ZodType<
  SkyScannerCarrier,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});

/** @internal */
export type SkyScannerCarrier$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const SkyScannerCarrier$outboundSchema: z.ZodType<
  SkyScannerCarrier$Outbound,
  z.ZodTypeDef,
  SkyScannerCarrier
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkyScannerCarrier$ {
  /** @deprecated use `SkyScannerCarrier$inboundSchema` instead. */
  export const inboundSchema = SkyScannerCarrier$inboundSchema;
  /** @deprecated use `SkyScannerCarrier$outboundSchema` instead. */
  export const outboundSchema = SkyScannerCarrier$outboundSchema;
  /** @deprecated use `SkyScannerCarrier$Outbound` instead. */
  export type Outbound = SkyScannerCarrier$Outbound;
}
